sonar.organization=Nicolas Manjarres Gonzalez
sonar.projectKey=NicolasManjarres11_bibliokeep
sonar.projectName=bibliokeep
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/mi-app/lcov.info
sonar.javascript.lcov.reportPaths=coverage/mi-app/lcov.info
sonar.exclusions=**/node_modules/**, **/dist/**
